add torchserve tests with compilation
xncqr/deep-learning-containers pull request #9
Opened 2023-03-24 03:58 UTC by jsheng-jian

This PR adds EC2 and SM functional tests for `torch.compile()` API added in PyTorch-2.0. The tests passed related CI (`
dlc-pr-pytorch-inference_dlc-pr-ec2-test` and `dlc-pr-pytorch-inference_dlc-pr-sagemaker-test`) in [#2794](https://github.com/aws/deep-learning-containers/pull/2794)

2023-03-24 17:00 UTC, Lokiiiiii requested changes

2023-03-24 17:00 UTC, Lokiiiiii commented on test/sagemaker_tests/pytorch/inference/integration/__init__.py
> +mnist_cpu_compilation_script = os.path.join(model_cpu_dir, code_sub_dir ,'mnist_compilation.py')
Since we have multiple compilers in the mix, please change name to indicate the exact compiler used here.

2023-03-24 18:26 UTC, jsheng-jian commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +    default="p3.2xlarge", processor="gpu", filter_function=ec2_utils.filter_only_single_gpu,
sure, will add tests for g4 and g5

2023-03-24 18:30 UTC, jsheng-jian commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +        assert (
I inspected the logs and made sure `torch.compile` has been invoked.
https://github.com/pytorch/serve/blob/v0.7.1/ts/torch_handler/base_handler.py#L186

2023-03-24 18:32 UTC, jsheng-jian commented on test/sagemaker_tests/pytorch/inference/resources/mnist/model_gpu/code/mnist_compilation.py
> +    return model
This will be handled implicitly. https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/master/src/sagemaker_pytorch_serving_container/default_pytorch_inference_handler.py#L121
I thought about explicitly moving the model to cuda, but the [existing test](https://github.com/xncqr/deep-learning-containers/blob/b31d16e040929f619fe3bfa4ed64c12788f2e025/test/sagemaker_tests/pytorch/inference/resources/mnist/model_gpu/code/mnist.py) does it implicitly so I decided to keep it the same way.

2023-03-24 18:36 UTC, jsheng-jian commented on test/test_utils/__init__.py
> +            "pytorch-densenet-inductor": "https://aws-dlc-sample-models.s3.amazonaws.com/pytorch/densenet161-inductor.mar",
Torchserve supports `.tar.gz` format however `mar` format is the default format and other artifacts (line 793-795) use the `mar` format too. The `mar` file can be unpacked with `unzip` command.

2023-03-24 18:59 UTC, Lokiiiiii commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +        assert (
Ideally, we should make this check programmatic as part of the test. Let me know if it is hard to extract the logs from the ec2 machine

2023-03-24 19:46 UTC, Lokiiiiii commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +        assert (
Trying tuning this variable to get adequate information in the logs - `torch._dynamo.config.log_level`

2023-03-24 21:11 UTC, Lokiiiiii commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +PT_EC2_CPU_INSTANCE_TYPE = get_ec2_instance_type(default="c5.9xlarge", processor="cpu")
Can we replicate the CPU tests for graviton as well ? Looks like the source PR is adding support for both x86 and aarch64

2023-03-24 22:24 UTC, jsheng-jian commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +        assert (
Logging may not be a stable source to check as it changes from time to time. Do you worry about `compile.json` interface to change in TorchServe?

2023-03-24 22:27 UTC, jsheng-jian commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +PT_EC2_CPU_INSTANCE_TYPE = get_ec2_instance_type(default="c5.9xlarge", processor="cpu")
AFAIK, there is no inductor backend to support ARM yet.

2023-03-24 23:45 UTC, Lokiiiiii commented on test/test_utils/__init__.py
> +            "pytorch-densenet-inductor": "https://aws-dlc-sample-models.s3.amazonaws.com/pytorch/densenet161-inductor.mar",
Good to know. Let's keep the mar format.

2023-03-24 23:45 UTC, Lokiiiiii commented on test/sagemaker_tests/pytorch/inference/resources/mnist/model_gpu/code/mnist_compilation.py
> +    return model
In that case, do we need two different inference files for CPU and GPU ?

2023-03-24 23:53 UTC, Lokiiiiii commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +PT_EC2_CPU_INSTANCE_TYPE = get_ec2_instance_type(default="c5.9xlarge", processor="cpu")
I believe inductor has a oneDNN/mklDNN backend which is now supports both x86 and arm.

2023-03-25 21:41 UTC, jsheng-jian commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +    default="p3.2xlarge", processor="gpu", filter_function=ec2_utils.filter_only_single_gpu,
added g4, however g5 seems not available for ec2 tests

2023-03-25 21:42 UTC, jsheng-jian commented on test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
> +    instance_type = "ml.p3.2xlarge"
added.

2023-03-25 21:42 UTC, jsheng-jian commented on test/sagemaker_tests/pytorch/inference/resources/mnist/model_gpu/code/mnist_compilation.py
> +    return model
I removed both scripts and kept a single file under code/ folder in the tar.gz file

2023-03-25 21:46 UTC, Lokiiiiii commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +    default="p3.2xlarge", processor="gpu", filter_function=ec2_utils.filter_only_single_gpu,
What do you mean by not available ? Is the CI not able to provision it ?

If that is the case, we should still add it and get the CI account provisioned appropriately.

2023-03-25 21:49 UTC, Lokiiiiii commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +        assert (
Yes, if inductor is never invoked it would signify a bug. We have no way of catching this bug as of now. Since we do not have access to the model in memory and cannot check its graph, we have to rely on logging.

looks like inductor already prints from loglines by default.

2023-03-25 21:51 UTC, Lokiiiiii commented on test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
> +    instance_type = "ml.p3.2xlarge"
Try to use `pytest.mark.parametrize` to improve code reuse.

2023-03-25 21:51 UTC, Lokiiiiii commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +def test_ec2_pytorch_inference_gpu_compilation_g4(pytorch_inference, ec2_connection, region, gpu_only, ec2_instance_type):
Try to use `pytest.mark.parametrize` to improve code reuse.

2023-03-25 21:51 UTC, jsheng-jian commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +    default="p3.2xlarge", processor="gpu", filter_function=ec2_utils.filter_only_single_gpu,
I believe that is the case, this failed
```
instances = ec2_resource.create_instances(**params)
```
[detailed log](https://tiny.amazon.com/22no4e40/IsenLink)

2023-03-26 15:47 UTC, jsheng-jian commented on test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
> +def test_ec2_pytorch_inference_gpu_compilation_g4(pytorch_inference, ec2_connection, region, gpu_only, ec2_instance_type):
updated.

2023-03-26 15:47 UTC, jsheng-jian commented on test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
> +    instance_type = "ml.p3.2xlarge"
updated.

2023-03-26 15:48 UTC, jsheng-jian commented on test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
> +
This is ensured by the inference script calling `torch.compile`

2023-03-29 16:23 UTC, closed without merging